---

- name: setup tower host for bigip demo
  hosts: localhost
  connection: local
  vars:
    tower_inventory: tower-demo
    tower_org: Default
    tower_project: playbooks
    tower_project_url: https://github.com/pharriso/ansible_network_demo.git
  tasks:
  - name: template out tower-cli file
    blockinfile:
      path: /home/{{ ansible_user_id }}/.tower_cli.cfg
      create: true
      block: |
        host: localhost
        username: admin
        password: ansible
        verify_ssl: false

  - name: create inventory in tower
    shell: tower-cli inventory create --name {{ tower_inventory }} --organization {{ tower_org }}

  - name: import inventory
    shell: tower-manage inventory_import --inventory-name={{ tower_inventory }}  --source=/home/{{ ansible_user_id }}/networking-workshop/lab_inventory/hosts
    become: true

  - name: create tower project
    shell: tower-cli project create --name {{ tower_project }} --organization {{ tower_org }} --scm-type git --scm-url {{ tower_project_url }} --scm-clean true --scm-delete-on-update true --scm-update-on-launch true --monitor

