---

- name: setup tower host for bigip demo
  hosts: localhost
  connection: local
  tasks:
  - name: template out tower-cli file
    blockinfile:
      path: /home/{{ ansible_user_id }}/.tower_cli.cfg
      create: true
      block: |
        host: localhost
        username: admin
        password: ansible
        verify_ssl: false

  - name: create inventory
    shell: tower-cli inventory create --name tower-demo --organization Default

