---

- name: setup tower host for bigip demo
  hosts: localhost
  connection: local
  vars:
    inventory_file: /home/{{ ansible_user_id }}/networking-workshop/lab_inventory/hosts
    tower_inventory: f5-tower-demo
    tower_org: Default
    tower_project: network-playbooks
    tower_project_url: https://github.com/pharriso/ansible_network_demo.git
  tasks:
  - name: template out tower-cli file
    blockinfile:
      path: /home/{{ ansible_user_id }}/.tower_cli.cfg
      create: true
      block: |
        host: localhost
        username: admin
        password: ansible
        verify_ssl: false

  - name: create f5 inventory in tower
    shell: tower-cli inventory create --name {{ tower_inventory }} --organization {{ tower_org }}

  - name: import f5 inventory
    shell: tower-manage inventory_import --inventory-name={{ tower_inventory }}  --source={{ inventory_file }}
    become: true

  - name: create tower project
    shell: tower-cli project create --name {{ tower_project }} --organization {{ tower_org }} --scm-type git --scm-url {{ tower_project_url }} --scm-clean false --scm-delete-on-update false --scm-update-on-launch true --monitor

  - name: create snow credential type
    shell: tower-cli credential_type create  --name snow --inputs @files/snow_cred_input  --injectors @files/snow_cred_inject --kind cloud

  - name: create snow credential
    shell: "tower-cli credential create --name snow --organization Default --credential-type snow --inputs='{\"snow_user\": \"admin\", \"snow_password\": \"{{ snow_password }}\", \"snow_instance\": \"{{ snow_instance }}\"}'"

  - name: create f5 credential
    tower_credential:
      username: admin
      password: admin
      kind: ssh
      organization: "{{ tower_org }}"
      name: f5

  - name: create f5 config job template
    shell:  tower-cli job_template create --name "Configure F5"  --job-type run --inventory {{ tower_inventory }} --project {{ tower_project }} --playbook bigip_config.yml --credential f5

  - name: create f5 member job template
    shell: tower-cli job_template create --name "Manage F5 member" --job-type run --inventory {{ tower_inventory }} --project {{ tower_project }} --playbook bigip_pool_member.yml --survey-enabled true --survey-spec @files/job_survey --credential f5

  - name: create f5 snow member job template
    shell: tower-cli job_template create --name "Manage F5 member ServiceNow" --job-type run --inventory {{ tower_inventory }} --project {{ tower_project }} --playbook bigip_pool_member_snow.yml --survey-enabled true --survey-spec @files/job_survey --ask-credential-on-launch true --ask-variables-on-launch true --credential f5

  - name: add snow credential to job template
    shell: tower-cli job_template associate_credential --job-template "Manage F5 member ServiceNow" --credential snow
