---

- name: setup tower host for bigip demo
  hosts: localhost
  connection: local
  vars:
    tower_inventory: tower-demo
    tower_org: Default
  tasks:
  - name: template out tower-cli file
    blockinfile:
      path: /home/{{ ansible_user_id }}/.tower_cli.cfg
      create: true
      block: |
        host: localhost
        username: admin
        password: ansible
        verify_ssl: false

  - name: create inventory in tower
    shell: tower-cli inventory create --name {{ tower_inventory }} --organization {{ tower_org }}

  - name: import inventory
    shell: tower-manage inventory_import --inventory-name={{ tower_inventory }}  --source=/home/{{ ansible_user_id }}/networking-workshop/lab_inventory/hosts
    become: true

