---
- name: grab f5 facts
  hosts: f5
  connection: local
  gather_facts: no


  tasks:

    - name: collect big-ip facts
      bigip_device_facts:
        gather_subset:
         - system-info
        server: "{{private_ip}}"
        user: "{{ansible_user}}"
        password: "{{ansible_ssh_pass}}"
        server_port: 8443
        validate_certs: no
      register: device_facts
