---
- name: update the snmp ro/rw strings
  hosts: cisco
  gather_facts: no
  connection: network_cli
  tasks:

    - name: ensure that the desired snmp strings are present
      ios_config:
        commands:
          - snmp-server community ansible-public RO
          - snmp-server community {{ lookup('cyberark.conjur.conjur_variable', 'cisco-snmp/{{ inventory_hostname }}') }} RW
          - snmp-server community ansible-test RO

    - name: ensure that routers are secure
      ios_config:
        src: files/secure_router.cfg
