---
- name: backup router configurations
  hosts: cisco
  connection: network_cli
  gather_facts: no
  vars:
    store_configs: host1

  tasks:

    - name: create /tmp/backup directory on {{store_configs}}
      vars:
        ansible_connection: ssh
      file:
        path: /tmp/backup
        state: directory
      delegate_to: "{{store_configs}}"
      run_once: yes
      become: yes

    - name: backup the config
      ios_config:
        backup: yes
      register: config_output

    - name: rename backup
      copy:
        src: "{{config_output.backup_path}}"
        dest: "./backup/{{inventory_hostname}}.config"

    - name: remove non config lines
      lineinfile:
        path: "./backup/{{inventory_hostname}}.config"
        line: "Building configuration..."
        state: absent

    - name: remove non config lines - regexp
      lineinfile:
        path: "./backup/{{inventory_hostname}}.config"
        regexp: 'Current configuration.*'
        state: absent

    - name: transfer file from this ansible host to {{store_configs}}
      copy:
        src: "./backup/{{inventory_hostname}}.config"
        dest: "/tmp/backup/{{inventory_hostname}}.config"
      delegate_to: "{{store_configs}}"
      become: yes

