---

- name: setup tower host for cisco demo
  hosts: localhost
  connection: local
  vars:
    inventory_file: /home/{{ ansible_user_id }}/networking-workshop/lab_inventory/hosts
    tower_inventory: cisco-tower-demo
    tower_org: Default
    tower_project: network-playbooks
    tower_project_url:  https://github.com/pharriso/ansible_network_demo.git
  tasks:
  - name: template out tower-cli file
    blockinfile:
      path: /home/{{ ansible_user_id }}/.tower_cli.cfg
      create: true
      block: |
        host: localhost
        username: admin
        password: ansible
        verify_ssl: false

  - name: create cisco inventory in tower
    shell: tower-cli inventory create --name {{ tower_inventory }} --organization {{ tower_org }}

  - name: import cisco inventory
    shell: tower-manage inventory_import --inventory-name={{ tower_inventory }}  --source={{ inventory_file }}
    become: true

  - name: create tower project
    shell: tower-cli project create --name {{ tower_project }} --organization {{ tower_org }} --scm-type git --scm-url {{ tower_project_url }} --scm-clean true --scm-delete-on-update true --scm-update-on-launch true --monitor

  - name: Add tower credential
    tower_credential:
      tower_verify_ssl: false
      name: cisco
      organization: "{{ tower_org }}"
      ssh_key_data: /home/{{ ansible_user_id }}/.ssh/aws-private.pem
      kind: ssh

  - name: create cisco banner job template
    shell:  tower-cli job_template create --name "Cisco Banner"  --job-type run --inventory {{ tower_inventory }} --project {{ tower_project }} --playbook cisco_backup.yml --ask-credential-on-launch true

    #- name: create f5 member job template
    #shell: tower-cli job_template create --name "Manage F5 member" --job-type run --inventory {{ tower_inventory }} --project {{ tower_project }} --playbook bigip_pool_member.yml --survey-enabled true --survey-spec @files/job_survey --ask-credential-on-launch true
