---
- name: gather information from routers
  hosts: cisco
  connection: network_cli
  gather_facts: no

  tasks:
    - name: gather router facts
      ios_facts:

    - name: display version
      debug:
        msg: "The IOS version is: {{ ansible_net_version }}"
      tags: show

    - name: display serial number
      debug:
        msg: "The serial number is:{{ ansible_net_serialnum }}"
      tags: show

    - name: COLLECT OUTPUT OF SHOW COMMANDS
      ios_command:
        commands:
          - show run | i hostname
          - show ip interface brief
      register: show_output
      tags: show

    - name: DISPLAY THE COMMAND OUTPUT
      debug:
        var: show_output
      tags: show
