---

- name: setup tower host for cisco demo
  hosts: localhost
  connection: local
  vars:
    inventory_file: /home/{{ ansible_user_id }}/networking-workshop/lab_inventory/hosts
    tower_inventory: cisco-tower-demo
    tower_org: Default
    tower_project: network-playbooks
    tower_project_url:  https://github.com/pharriso/ansible_network_demo.git
    cisco_ssh_key: /home/{{ ansible_user_id }}/.ssh/aws-private.pem
  tasks:
  - name: template out tower-cli file
    blockinfile:
      path: /home/{{ ansible_user_id }}/.tower_cli.cfg
      create: true
      block: |
        host: localhost
        username: admin
        password: ansible
        verify_ssl: false

  - name: create cisco inventory in tower
    shell: tower-cli inventory create --name {{ tower_inventory }} --organization {{ tower_org }}

  - name: copy inventory
    copy:
      src: "{{ inventory_file }}"
      dest: "{{ inventory_file }}-tower"
      remote_src: yes

  - name: remove key from inventory 
    replace:
      path: "{{ inventory_file }}-tower"
      regexp: '^ansible_ssh_private_key_file'
      replace: '#ansible_ssh_private_key_file'

  - name: import cisco inventory
    shell: tower-manage inventory_import --inventory-name={{ tower_inventory }}  --source={{ inventory_file }}-tower
    become: true

  - name: create tower project
    shell: tower-cli project create --name {{ tower_project }} --organization {{ tower_org }} --scm-type git --scm-url {{ tower_project_url }} --scm-clean true --scm-delete-on-update true --scm-update-on-launch true --monitor

  - name: Add tower credential
    tower_credential:
      tower_verify_ssl: false
      name: cisco
      organization: "{{ tower_org }}"
      ssh_key_data: "{{ cisco_ssh_key }}"
      kind: ssh

  - name: create cisco backup job template
    shell:  tower-cli job_template create --name "Cisco Backup"  --job-type run --inventory {{ tower_inventory }} --project {{ tower_project }} --playbook cisco_backup.yml --credential cisco

  - name: create cisco restore job template
    shell:  tower-cli job_template create --name "Cisco Restore"  --job-type run --inventory {{ tower_inventory }} --project {{ tower_project }} --playbook cisco_restore.yml --credential cisco

  - name: create cisco config job template
    shell:  tower-cli job_template create --name "Cisco Config"  --job-type run --inventory {{ tower_inventory }} --project {{ tower_project }} --playbook cisco_config.yml --credential cisco
