---
- name: SETUP TOWER WORKFLOW
  hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  vars:
    tower_jobs:
      - {"name": "cisco archive backup", "playbook": "archive_backup.yml" }
      - {"name": "cisco archive restore", "playbook": "archive_restore.yml" }
      - {"name": "cisco ping test", "playbook": "network_ping.yml" }
      - {"name": "cisco configure interface", "playbook": "network_interface.yml" }
    inventory: Cisco rhpds
    project: cisco playbooks
    credential: cisco rhpds
  tasks:

    - name: CREATE TOWER JOB TEMPLATES
      tower_job_template:
        name: "{{ item.name }}"
        job_type: "run"
        inventory: "{{ inventory }}"
        project: "{{ project }}"
        playbook: "{{ item.playbook }}"
        credential: "{{ credential }}"
        tower_username: admin
        tower_password: Redhat123
        tower_host: https://localhost
        validate_certs: false
      loop: "{{ tower_jobs }}"

    - name: CREATE TOWER WORKFLOW
      tower_workflow_template:
        tower_username: admin
        tower_password: Redhat123
        tower_host: https://localhost
        validate_certs: false
        name: cisco workflow
        schema: "{{ lookup('file', 'workflow.json') }}"
